### ISSUE TITLE
MessageBodyProviderNotFoundException upon calling getTestConfigurations

### ISSUE THREAD

**Issue by pligor** [loadimpact/loadimpact-sdk-java#1]
When calling this line:
`final List<TestConfiguration> configurations = client.getTestConfigurations();`

We are receiving this exception:

```
        [error] Test AppTest.renderTemplate failed: com.loadimpact.exception.ApiException: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=application/json; charset=utf-8, type=interface javax.json.JsonArray, genericType=interface javax.json.JsonArray.
        [error]     at com.loadimpact.ApiTokenClient.invoke(ApiTokenClient.java:457)
        [error]     at com.loadimpact.ApiTokenClient.invoke(ApiTokenClient.java:266)
        [error]     at com.loadimpact.ApiTokenClient.getTestConfigurations(ApiTokenClient.java:520)
        [error]     at AppTest.renderTemplate(AppTest.java:48)
        [error]     ...
        [error] Caused by: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=application/json; charset=utf-8, type=interface javax.json.JsonArray, genericType=interface javax.json.JsonArray.
        [error]     at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:207)
```

Do we have to work with java 7 or java 6 is enough ?
Thank you

**Comment by robingustafsson** [comment]
Java 6 should work, we test against Java 6 and 7. We made a new release of the SDK ~1 hour ago that should fix this issue: https://github.com/loadimpact/loadimpact-sdk-java/releases

Thanks for reporting.
